"""Optional browser smoke check. Requires Python Playwright, Chromium CDP on 9223, and demo on 5080."""
import os
from playwright.sync_api import sync_playwright, expect

with sync_playwright() as p:
    browser = p.chromium.connect_over_cdp(os.environ.get('CHAT_CDP_URL', 'http://127.0.0.1:9223'))
    context = browser.new_context()
    page = context.new_page()
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.goto(os.environ.get('CHAT_DEMO_URL', 'http://127.0.0.1:5080'))
    expect(page.locator('#aiAssistantPanel')).to_be_hidden()
    launcher = page.get_by_role('button', name='Open AI assistant', exact=True)
    launcher.click()
    expect(page.locator('#aiAssistantPanel')).to_be_visible()
    expect(page.get_by_label('Your question')).to_be_focused()
    field = page.get_by_label('Your question')
    field.fill('Where is order 45821?')
    field.press('Enter')
    expect(page.locator('article.assistant')).to_have_count(2)
    expect(page.locator('article.assistant').last).to_contain_text('In Transit')
    field.fill('What is the procedure for damaged goods?')
    page.get_by_role('button', name='Send', exact=True).click()
    expect(page.locator('.source')).to_have_count(1)
    expect(page.locator('article.assistant').last).to_contain_text('FICTIONAL DEMO ONLY')
    field.fill('order 99999')
    page.get_by_role('button', name='Send', exact=True).click()
    expect(page.locator('#aiChatError')).to_contain_text('unavailable')
    page.get_by_role('button', name='New conversation').click()
    expect(page.locator('article')).to_have_count(1)
    page.get_by_role('button', name='Close AI assistant', exact=True).click()
    expect(page.locator('#aiAssistantPanel')).to_be_hidden()
    expect(launcher).to_be_focused()
    launcher.press('Enter')
    expect(page.locator('#aiAssistantPanel')).to_be_visible()
    expect(page.locator('article')).to_have_count(1)
    page.get_by_label('Your question').press('Escape')
    expect(page.locator('#aiAssistantPanel')).to_be_hidden()
    page.get_by_role('button', name='AI assistant', exact=True).click()
    expect(page.locator('#aiAssistantPanel')).to_be_visible()
    page.route('**/api/chat/message', lambda route: route.fulfill(
        json={'conversationId': 'test-conversation', 'message': '<img src=x onerror=alert(1)>', 'requestId': 'test-request', 'sources': []}))
    field.fill('Test safe rendering')
    page.get_by_role('button', name='Send', exact=True).click()
    expect(page.locator('article.assistant').last).to_contain_text('<img src=x onerror=alert(1)>')
    expect(page.locator('#aiChatMessages img')).to_have_count(0)
    page.set_viewport_size({'width': 375, 'height': 667})
    expect(page.locator('#aiAssistantPanel')).to_be_visible()
    assert page.locator('#aiAssistantPanel').bounding_box()['width'] == 375
    assert not errors, errors
    print('PASS: launcher, close/reopen, Escape, focus restoration, mobile panel, keyboard send, answer, conversation continuation, sources, denied-order error, reset, text-only rendering; no uncaught errors')
    context.close()
    browser.close()
